#!/bin/sh
#
# Start a new xsession.

# Be boring.
xsetroot -solid white

# We might have some local binaries in ~/bin/, e.g. a custom surf.
export PATH=/home/odroid/bin:/usr/local/bin:$PATH

# Hide mouse.
xdotool mousemove 2000 2000

# If X has restarted then tmux with the kantinfo script may already
# be running - if so, kill it before we start a new one.
tmux kill-session -t kantinfo

# Start a new tmux running the kantinfo script.
dbus-launch tmux new-session -s kantinfo -d \
            'cd kantinfo; ./kantinfo.py --random ../cokepc/content; bash'

# Start the barebones window manager.
matchbox-window-manager -use_titlebar no
